### PR TITLE
Refactoring

### PR DESCRIPTION
**Pull request by iamnottheway**
Used toplevel windows instead of the parent windows.

* Added a splash screen
* When login button is pressed, it now shows a text message inside the GUI

### CODE REVIEW

**Comment by coderaavan** [comment]
Sorry @HarowitzBlack. Festival days are going in India so I wasn't able to reply. I will test the changes and merge them if they work fine 👍

**Comment by coderaavan** [comment]
@HarowitzBlack I ran into an issue that after splash screen there comes a blank window with no input fields and buttons. @CSaratakij Is this happening to u too?

**Comment by CSaratakij** [comment]
@coderaavan Confirmed, blank screen after splash screen. (Investigating)

**Comment by CSaratakij** [comment]
@coderaavan Fixed it.
Waiting @HarowitzBlack to pull my request at HarowitzBlack/fbChatPython#2
(after that, it should be functional)

**Comment by iamnottheway** [comment]
@coderaavan  Happy Diwali dude! 

@CSaratakij  merged it! And thanks for fixing the bug.

**Comment by CSaratakij** [comment]
@HarowitzBlack dont forget to merge my change into your remote “refactoring” branch xD 
(merge master into refactoring)
(sry, when I open pull request I target the wrong branch..)

**Comment by coderaavan** [comment]
@HarowitzBlack Thanks for the wish :)! And I am still facing the same issue.

**Comment by CSaratakij** [comment]
@coderaavan He didnt merge my change into his refactoring branch. but in master.
he start new pull request in #48 and that branch contain my fix.

**Pull request merged**
