### PR TITLE
Fixed the imports to python2 and fb new login style

### PR DESCRIPTION
**Pull request by iamnottheway**

### CODE REVIEW

**Comment by CSaratakij** [comment]
@HarowitzBlack Please remove binary file and temponary file (.py~, .pyc)

**Comment by CSaratakij** [comment]
@HarowitzBlack last one (“formlogin.py~”) xD

**Comment by iamnottheway** [comment]
@CSaratakij Can it merge now? 😂

**Comment by CSaratakij** [comment]
formlogin.py~ is a temponary file (maybe some editor use it. please remove it in ur repository xD)

**Comment by iamnottheway** [comment]
@CSaratakij into the trash !😂🚀

**Comment by CSaratakij** [comment]
wait for @coderaavan. (you good to go now~) xD (hooray~)

**Comment by coderaavan** [comment]
@HarowitzBlack while testing this commit I found that there's an import error that "cannot import name font". Please look into the issue. @CSaratakij Can u please take a look?

**Comment by CSaratakij** [comment]
@coderaavan Sure~, my guess -> font familiy Ubuntu is not exist in ur system?
Im currently reading this : http://www.tkdocs.com/tutorial/fonts.html

**Comment by CSaratakij** [comment]
@coderaavan As I expect. Mine system doesnt have Ubuntu font family too.
loading of Ubuntu font is in formloginfailure. 
Whenever it cant load font, It will crash program.

**Comment by CSaratakij** [comment]
Sry, turns out that is not the case - -. (will try to fix it)

**Comment by CSaratakij** [comment]
@coderaavan Fixed it. turns out Font is not in Tkinter module but in tkFont.
fixed by chage import line of font to “import tkFont as font”

**Comment by iamnottheway** [comment]
@coderaavan removed font style. Will add it once this project has been ported to python3. I think that this project should support both versions of python. Any thoughts on this?

**Comment by iamnottheway** [comment]
@CSaratakij  I did it because I use python3 and the project uses python2. When I run the script using `from tkinter import font` I don't get an error. So, maybe after porting it to python3 I'll add it back. For now, let it be.

**Comment by CSaratakij** [comment]
@HarowitzBlack Okay then. Personally, porting to python3 would be nice 👍.

**Comment by iamnottheway** [comment]
@CSaratakij  I ported it. I'll send a PR now

**Comment by CSaratakij** [comment]
@HarowitzBlack I forgot to mention. @coderaavan  want this to be python2 for now.
Maybe open a new branch for this specific port?

**Comment by iamnottheway** [comment]
This project works on both versions now. It's 2017, python2 is old!!!😆

**Comment by coderaavan** [comment]
@HarowitzBlack  @CSaratakij I agree that this project should work on both versions of Python. Actually I just learned Python and made a project to get more familiar with. @HarowitzBlack I will test your new PR and should I close this one?

**Comment by iamnottheway** [comment]
@coderaavan  please test my PR and let me know if there are any errors and you can close this one.

**Pull request merged**
